package wxpay

const (
	FAIL                         = "FAIL"
	SUCCESS                      = "SUCCESS"
	HMACSHA256                   = "HMACSHA256"
	MD5                          = "MD5"
	FIELD_SIGN                   = "sign"
	FIELD_SIGN_TYPE              = "sign_type"
	MICROPAY_URL                 = "https://api.mch.weixin.qq.com/pay/micropay"
	UNIFIEDORDER_URL             = "https://api.mch.weixin.qq.com/pay/unifiedorder"
	ORDERQUERY_URL               = "https://api.mch.weixin.qq.com/pay/orderquery"
	REVERSE_URL                  = "https://api.mch.weixin.qq.com/secapi/pay/reverse"
	CLOSEORDER_URL               = "https://api.mch.weixin.qq.com/pay/closeorder"
	REFUND_URL                   = "https://api.mch.weixin.qq.com/secapi/pay/refund"
	REFUNDQUERY_URL              = "https://api.mch.weixin.qq.com/pay/refundquery"
	DOWNLOADBILL_URL             = "https://api.mch.weixin.qq.com/pay/downloadbill"
	REPORT_URL                   = "https://api.mch.weixin.qq.com/payitil/report"
	SHORTURL_URL                 = "https://api.mch.weixin.qq.com/tools/shorturl"
	AUTHCODETOOPENID_URL         = "https://api.mch.weixin.qq.com/tools/authcodetoopenid"
	SANDBOX_MICROPAY_URL         = "https://api.mch.weixin.qq.com/sandboxnew/pay/micropay"
	SANDBOX_UNIFIEDORDER_URL     = "https://api.mch.weixin.qq.com/sandboxnew/pay/unifiedorder"
	SANDBOX_ORDERQUERY_URL       = "https://api.mch.weixin.qq.com/sandboxnew/pay/orderquery"
	SANDBOX_REVERSE_URL          = "https://api.mch.weixin.qq.com/sandboxnew/secapi/pay/reverse"
	SANDBOX_CLOSEORDER_URL       = "https://api.mch.weixin.qq.com/sandboxnew/pay/closeorder"
	SANDBOX_REFUND_URL           = "https://api.mch.weixin.qq.com/sandboxnew/secapi/pay/refund"
	SANDBOX_REFUNDQUERY_URL      = "https://api.mch.weixin.qq.com/sandboxnew/pay/refundquery"
	SANDBOX_DOWNLOADBILL_URL     = "https://api.mch.weixin.qq.com/sandboxnew/pay/downloadbill"
	SANDBOX_REPORT_URL           = "https://api.mch.weixin.qq.com/sandboxnew/payitil/report"
	SANDBOX_SHORTURL_URL         = "https://api.mch.weixin.qq.com/sandboxnew/tools/shorturl"
	SANDBOX_AUTHCODETOOPENID_URL = "https://api.mch.weixin.qq.com/sandboxnew/tools/authcodetoopenid"
)
